apiVersion: batch/v1
kind: Job
metadata:
  generateName: mock-app-post-sync-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: mock-app-sync
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "GET"
          - "http://localhost:8081/teams/main/pipelines/canary-pipeline/resources/manual/check/webhook?webhook_token=supers3cret"
      restartPolicy: Never
  backoffLimit: 2