apiVersion: batch/v1
kind: Job
metadata:
  generateName: mock-app-post-sync-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: mock-app-sync
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "GET"
          - "https://webhook.site/4039e3d1-8dc6-40b7-900f-1659c6a1e030"
      restartPolicy: Never
  backoffLimit: 2